# Generated by Django 5.2.6 on 2025-09-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_cliente_proveedor_producto_remito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='domicilio',
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='provincia',
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
