# Generated by Django 5.2.6 on 2025-10-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
